=== guimagalhaes/aga/spec/aga.dtd
<!ELEMENT AGA (HEAD, ACTOR+, TAPE+, INSTANCE+)>
<!ATTLIST AGA
	VERSION CDATA #FIXED "2.0"
	WIDTH CDATA #REQUIRED
	HEIGHT CDATA #REQUIRED
	BACKGROUND CDATA #REQUIRED	
	FRAMERATE CDATA #REQUIRED
	REPEAT CDATA #IMPLIED>
<!ELEMENT HEAD (TITLE, AUTHOR, SUBJECT)>
<!ELEMENT TITLE (#PCDATA)>
<!ELEMENT AUTHOR (#PCDATA)>
<!ELEMENT SUBJECT (#PCDATA)>
<!ELEMENT ACTOR (OUTPUT*, DESCF?, TRANSF)>
<!ATTLIST ACTOR
	ID CDATA #REQUIRED
	STATES CDATA #REQUIRED
	SYMBOLS CDATA #REQUIRED>	
<!ELEMENT OUTPUT EMPTY>
<!ATTLIST OUTPUT
	ID CDATA #REQUIRED
	SOURCE CDATA #REQUIRED
	X CDATA #REQUIRED
	Y CDATA #REQUIRED>
<!ELEMENT DESCF (DESCRIPTION+)>
<!ELEMENT DESCRIPTION (#PCDATA)>
<!ATTLIST DESCRIPTION
	STATE CDATA #REQUIRED>
<!ELEMENT TRANSF (FROM+)>
<!ELEMENT FROM (TO+)>
<!ATTLIST FROM 
	STATE CDATA #REQUIRED>
<!ELEMENT TO EMPTY>
<!ATTLIST TO
	STATE CDATA #REQUIRED
            	SYMBOL CDATA #REQUIRED
	OUTPUT CDATA #IMPLIED>
<!ELEMENT TAPE (CEL|GROUP)+>
<!ATTLIST TAPE
	ID CDATA #REQUIRED>
<!ELEMENT CEL EMPTY>
<!ATTLIST CEL
	SYMBOL CDATA #REQUIRED
	TIME CDATA #REQUIRED
	FN CDATA #IMPLIED>
<!ELEMENT GROUP (CEL|GROUP)+>
<!ATTLIST GROUP
	ITERATION CDATA #REQUIRED>

=== guimagalhaes/aga/spec/exemplo1.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE AGA SYSTEM "aga.dtd">

<AGA VERSION="2.0" WIDTH="200" HEIGHT="150" BACKGROUND="255 255 255" FRAMERATE="10" REPEAT="LOOP">

	<!-- O FRAMERATE INDICA O NUMERO DE QUADROS POR SEGUNDO. PARA ESTE EXEMPLO SERA CRIADO UM FRAME A CADA 100 MS.-->
	<!-- O EFEITO ESPERADO EH O MESMO QUE O DA LINGUAGEM AgaML 1.2 -->	

	
	<HEAD>
		<TITLE>Bigato</TITLE>
		<AUTHOR>Fernando Accorsi</AUTHOR>
		<SUBJECT>Exemplo 1 em AgaMl 2.0</SUBJECT>
	</HEAD>

	<!-- DEFINICAO DOS AUTOMATOS DOS ATORES BICHO E MACA. A ORDEM NAO IMPORTA. -->
	
	<ACTOR ID="BICHO" STATES="6" SYMBOLS="2">
		<OUTPUT ID="1" SOURCE="contraida.gif" X="0" Y="13"/>
		<OUTPUT ID="2" SOURCE="estendida.gif" X="0" Y="42"/>
		<OUTPUT ID="3" SOURCE="aberta.gif" X="0" Y="22"/>
		<OUTPUT ID="4" SOURCE="alerta.gif" X="0" Y="0"/>
		<OUTPUT ID="5" SOURCE="rindo.gif" X="0" Y="0"/>
		
		<DESCF>
			<DESCRIPTION STATE="4">Boca aberta</DESCRIPTION>
			<DESCRIPTION STATE="3">Alerta</DESCRIPTION>
			<DESCRIPTION STATE="6">Rindo</DESCRIPTION>
		</DESCF>
		<TRANSF>
			<FROM STATE="1">
				<TO STATE="2" SYMBOL="1" OUTPUT="2"/>
			</FROM>
			<FROM STATE="2">
				<TO STATE="5" SYMBOL="1" OUTPUT="1"/>
				<TO STATE="4" SYMBOL="2" OUTPUT="3"/>
				<TO STATE="3" SYMBOL="3" OUTPUT="4"/>
			</FROM>
			<FROM STATE="3">
				<TO STATE="2" SYMBOL="1" OUTPUT="2"/>
				<TO STATE="6" SYMBOL="2" OUTPUT="5"/>
			</FROM>
			<FROM STATE="4">
				<TO STATE="2" SYMBOL="1" OUTPUT="2"/>
			</FROM>
			<FROM STATE="5">
				<TO STATE="2" SYMBOL="1" OUTPUT="2"/>
			</FROM>
			<FROM STATE="6">
				<TO STATE="3" SYMBOL="1" OUTPUT="4"/>
			</FROM>
		</TRANSF>
	</ACTOR>

	<ACTOR ID="MACA" STATES="3" SYMBOLS="1">
		<OUTPUT ID="1" SOURCE="maca.gif" X="0" Y="0"/>
		<OUTPUT ID="2" SOURCE="mordida.gif" X="0" Y="0"/>
		
		<DESCF>
			<DESCRIPTION STATE="3">Maca Mordida</DESCRIPTION>
		</DESCF>
		<TRANSF>
			<FROM STATE="1">
				<TO STATE="2" SYMBOL="1" OUTPUT="1"/>				
			</FROM>
			<FROM STATE="2">
				<TO STATE="3" SYMBOL="1" OUTPUT="2"/>				
			</FROM>
		</TRANSF>	
	</ACTOR>


	<!-- DEFINICAO DAS FITAS DE ENTRADA. A ORDEM NAO IMPORTA-->
	<!-- O TEMPO EH DEFINIDO EM MILeSIMOS DE SEGUNDO, NAO MAIS COMO UM MULTIPLICADOR DA BASE-->

	<TAPE ID="COMER">
		<CEL SYMBOL="1" TIME="200" FN="TRANSLATE 2 50 N"/>
		<CEL SYMBOL="1" TIME="200" FN="TRANSLATE 30 0 Y"/>
		<CEL SYMBOL="1" TIME="200"/>
		<CEL SYMBOL="2" TIME="200"/>
		<CEL SYMBOL="1" TIME="200"/>		
	</TAPE>

	<TAPE ID="RIR">
		<CEL SYMBOL="3" TIME="200"/>
		<CEL SYMBOL="2" TIME="500"/>
		<CEL SYMBOL="1" TIME="200"/>
	</TAPE>

	<TAPE ID="MORDIDA">
		<CEL SYMBOL="1" TIME="800" FN="TRANSLATE 142 70 N"/>
		<CEL SYMBOL="1" TIME="1100"/>
	</TAPE>


	<!-- DEFINICAO DAS INSTANCIAS. PARA CADA ATOR PODEM SER DEFINIDAS VARIAS INSTANCIAS.-->
	<!-- QUANDO UMA FITA ACABA EH INICIADA OUTRA COMO SE FOSSE A CONTINUACAO DA FITA.-->

	<INSTANCE ID="BICHO FAMINTO" ACTOR="BICHO" ORDER="1">
		<USE TAPE="COMER"/>
		<USE TAPE="RIR"/>
	</INSTANCE>	

	<INSTANCE ID="MACA VITIMA" ACTOR="MACA" ORDER="2">
		<USE TAPE="MORDIDA"/>
	</INSTANCE>
</AGA>
